import = [" /home/kali_37/.config/alacritty/keyboard.toml ", "/home/kali_37/.config/alacritty/dracula.toml"]

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true


[font]
size = 12

[font.bold]
family = "Mononoki Nerd Font"
style = "Light"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "Light Italic"

[font.italic]
family = "Mononoki Nerd Font"
style = "Extra Light Italic"

[font.normal]
family = "Mononoki Nerd Font"
style = "ExtraLight"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "Space"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "I"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "C"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ClearSelection"
key = "LBracket"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Y"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "E"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "G"
mode = "Vi"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "B"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "F"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mode = "Vi"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "V"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mode = "Vi"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mode = "Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Open"
key = "Return"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "K"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "J"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "H"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "L"
mode = "Vi"

[[keyboard.bindings]]
action = "Up"
key = "Up"
mode = "Vi"

[[keyboard.bindings]]
action = "Down"
key = "Down"
mode = "Vi"

[[keyboard.bindings]]
action = "Left"
key = "Left"
mode = "Vi"

[[keyboard.bindings]]
action = "Right"
key = "Right"
mode = "Vi"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi"

[[keyboard.bindings]]
action = "Last"
key = "Key4"
mode = "Vi"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "Key6"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "High"
key = "H"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Middle"
key = "M"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Low"
key = "L"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SemanticLeft"
key = "B"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRight"
key = "W"
mode = "Vi"

[[keyboard.bindings]]
action = "SemanticRightEnd"
key = "E"
mode = "Vi"

[[keyboard.bindings]]
action = "WordLeft"
key = "B"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRight"
key = "W"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "WordRightEnd"
key = "E"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Bracket"
key = "Key5"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "Slash"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Slash"
mode = "Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mode = "Vi"
mods = "Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity =0.92

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10


